In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn


In [21]:
df_test = pd.read_csv("test.csv",index_col=0)

In [22]:
df_test.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1461          20       RH         80.0    11622   Pave   NaN      Reg   
1462          20       RL         81.0    14267   Pave   NaN      IR1   
1463          60       RL         74.0    13830   Pave   NaN      IR1   
1464          60       RL         78.0     9978   Pave   NaN      IR1   
1465         120       RL         43.0     5005   Pave   NaN      IR1   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
Id                                    ...                                      
1461         Lvl    AllPub    Inside  ...         120        0    NaN  MnPrv   
1462         Lvl    AllPub    Corner  ...           0        0    NaN    NaN   
1463         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv   
1464         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1465         HLS    AllPub    Inside  ...         144        0    NaN    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
Id                                                                 
1461         NaN       0       6    2010        WD         Normal  
1462        Gar2   12500       6    2010        WD         Normal  
1463         NaN       0       3    2010        WD         Normal  
1464         NaN       0       6    2010        WD         Normal  
1465         NaN       0       1    2010        WD         Normal  

[5 rows x 79 columns]

In [23]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1461 to 2919
Data columns (total 79 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1459 non-null   int64  
 1   MSZoning       1455 non-null   object 
 2   LotFrontage    1232 non-null   float64
 3   LotArea        1459 non-null   int64  
 4   Street         1459 non-null   object 
 5   Alley          107 non-null    object 
 6   LotShape       1459 non-null   object 
 7   LandContour    1459 non-null   object 
 8   Utilities      1457 non-null   object 
 9   LotConfig      1459 non-null   object 
 10  LandSlope      1459 non-null   object 
 11  Neighborhood   1459 non-null   object 
 12  Condition1     1459 non-null   object 
 13  Condition2     1459 non-null   object 
 14  BldgType       1459 non-null   object 
 15  HouseStyle     1459 non-null   object 
 16  OverallQual    1459 non-null   int64  
 17  OverallCond    1459 non-null   int64  
 18  YearB

In [17]:
df_train = pd.read_csv("train.csv",index_col=0)

In [18]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSSubClass     1460 non-null   int64  
 1   MSZoning       1460 non-null   object 
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64  
 4   Street         1460 non-null   object 
 5   Alley          91 non-null     object 
 6   LotShape       1460 non-null   object 
 7   LandContour    1460 non-null   object 
 8   Utilities      1460 non-null   object 
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [19]:
df_train.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [31]:
df_train.isna().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [ ]:
#gestion des nan

In [34]:
df_train["LotFrontage"].value_counts(dropna=False)

NaN      259
60.0     143
70.0      70
80.0      69
50.0      57
        ... 
137.0      1
38.0       1
33.0       1
150.0      1
46.0       1
Name: LotFrontage, Length: 111, dtype: int64

In [36]:
df_train["LotFrontage"].unique()

array([ 65.,  80.,  68.,  60.,  84.,  85.,  75.,  nan,  51.,  50.,  70.,
        91.,  72.,  66., 101.,  57.,  44., 110.,  98.,  47., 108., 112.,
        74., 115.,  61.,  48.,  33.,  52., 100.,  24.,  89.,  63.,  76.,
        81.,  95.,  69.,  21.,  32.,  78., 121., 122.,  40., 105.,  73.,
        77.,  64.,  94.,  34.,  90.,  55.,  88.,  82.,  71., 120., 107.,
        92., 134.,  62.,  86., 141.,  97.,  54.,  41.,  79., 174.,  99.,
        67.,  83.,  43., 103.,  93.,  30., 129., 140.,  35.,  37., 118.,
        87., 116., 150., 111.,  49.,  96.,  59.,  36.,  56., 102.,  58.,
        38., 109., 130.,  53., 137.,  45., 106., 104.,  42.,  39., 144.,
       114., 128., 149., 313., 168., 182., 138., 160., 152., 124., 153.,
        46.])

In [37]:
#Au vue de la définition de cette variable les nan doivent être changé en 0 (pas de rue connectée)
df_train["LotFrontage"] = df_train["LotFrontage"].fillna(0.)

In [44]:
df_train["Alley"].unique()

array([nan, 'Grvl', 'Pave'], dtype=object)

In [45]:
#au vue de la définition les nan devrait être des "sans" 
df_train["Alley"] = df_train["Alley"].fillna("NoAl")

In [46]:
df_train["MasVnrType"].unique()

array(['BrkFace', 'None', 'Stone', 'BrkCmn', nan], dtype=object)

In [71]:
df_train["MasVnrArea"].unique()

array([1.960e+02, 0.000e+00, 1.620e+02, 3.500e+02, 1.860e+02, 2.400e+02,
       2.860e+02, 3.060e+02, 2.120e+02, 1.800e+02, 3.800e+02, 2.810e+02,
       6.400e+02, 2.000e+02, 2.460e+02, 1.320e+02, 6.500e+02, 1.010e+02,
       4.120e+02, 2.720e+02, 4.560e+02, 1.031e+03, 1.780e+02, 5.730e+02,
       3.440e+02, 2.870e+02, 1.670e+02, 1.115e+03, 4.000e+01, 1.040e+02,
       5.760e+02, 4.430e+02, 4.680e+02, 6.600e+01, 2.200e+01, 2.840e+02,
       7.600e+01, 2.030e+02, 6.800e+01, 1.830e+02, 4.800e+01, 2.800e+01,
       3.360e+02, 6.000e+02, 7.680e+02, 4.800e+02, 2.200e+02, 1.840e+02,
       1.129e+03, 1.160e+02, 1.350e+02, 2.660e+02, 8.500e+01, 3.090e+02,
       1.360e+02, 2.880e+02, 7.000e+01, 3.200e+02, 5.000e+01, 1.200e+02,
       4.360e+02, 2.520e+02, 8.400e+01, 6.640e+02, 2.260e+02, 3.000e+02,
       6.530e+02, 1.120e+02, 4.910e+02, 2.680e+02, 7.480e+02, 9.800e+01,
       2.750e+02, 1.380e+02, 2.050e+02, 2.620e+02, 1.280e+02, 2.600e+02,
       1.530e+02, 6.400e+01, 3.120e+02, 1.600e+01, 

In [64]:
records = df_train[df_train["MasVnrType"].isna()==True]
records["MasVnrArea"]

Id
235    NaN
530    NaN
651    NaN
937    NaN
974    NaN
978    NaN
1244   NaN
1279   NaN
Name: MasVnrArea, dtype: float64

In [65]:
#Donc avec les definitions, on choisi nan -> "None" et NaN ->0.000e00
df_train["MasVnrType"] = df_train["MasVnrType"].fillna("None")
df_train["MasVnrArea"] = df_train["MasVnrArea"].fillna(0.0e+00)

In [66]:
df_train["MasVnrType"].unique()

array(['BrkFace', 'None', 'Stone', 'BrkCmn'], dtype=object)

In [69]:
df_train["MasVnrArea"].value_counts(dropna=False)

0.0      869
180.0      8
72.0       8
108.0      8
120.0      7
        ... 
562.0      1
89.0       1
921.0      1
762.0      1
119.0      1
Name: MasVnrArea, Length: 327, dtype: int64

In [ ]:
 #BsmtQual       1423 non-null   object 
 #30  BsmtCond       1423 non-null   object 
 #31  BsmtExposure   1422 non-null   object 
 #32  BsmtFinType1   1423 non-null   object 
 #33  BsmtFinSF1     1460 non-null   int64  
 #34  BsmtFinType2   1422 non-null   object

In [75]:
df_train["BsmtQual"].unique()

array(['Gd', 'TA', 'Ex', nan, 'Fa'], dtype=object)

In [72]:
df_train["BsmtCond"].unique()

array(['TA', 'Gd', nan, 'Fa', 'Po'], dtype=object)

In [73]:
df_train["BsmtExposure"].unique()

array(['No', 'Gd', 'Mn', 'Av', nan], dtype=object)

In [77]:
df_train["BsmtFinType1"].unique()

array(['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', nan, 'LwQ'], dtype=object)

In [78]:
df_train["BsmtFinType2"].unique()

array(['Unf', 'BLQ', nan, 'ALQ', 'Rec', 'LwQ', 'GLQ'], dtype=object)

In [81]:
df_train[df_train["BsmtExposure"].isna() == True][["BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1","BsmtFinType2"]]

BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2
Id                                                           
18        NaN      NaN          NaN          NaN          NaN
40        NaN      NaN          NaN          NaN          NaN
91        NaN      NaN          NaN          NaN          NaN
103       NaN      NaN          NaN          NaN          NaN
157       NaN      NaN          NaN          NaN          NaN
183       NaN      NaN          NaN          NaN          NaN
260       NaN      NaN          NaN          NaN          NaN
343       NaN      NaN          NaN          NaN          NaN
363       NaN      NaN          NaN          NaN          NaN
372       NaN      NaN          NaN          NaN          NaN
393       NaN      NaN          NaN          NaN          NaN
521       NaN      NaN          NaN          NaN          NaN
533       NaN      NaN          NaN          NaN          NaN
534       NaN      NaN          NaN          NaN          NaN
554       NaN      NaN          NaN          NaN          NaN
647       NaN      NaN          NaN          NaN          NaN
706       NaN      NaN          NaN          NaN          NaN
737       NaN      NaN          NaN          NaN          NaN
750       NaN      NaN          NaN          NaN          NaN
779       NaN      NaN          NaN          NaN          NaN
869       NaN      NaN          NaN          NaN          NaN
895       NaN      NaN          NaN          NaN          NaN
898       NaN      NaN          NaN          NaN          NaN
949        Gd       TA          NaN          Unf          Unf
985       NaN      NaN          NaN          NaN          NaN
1001      NaN      NaN          NaN          NaN          NaN
1012      NaN      NaN          NaN          NaN          NaN
1036      NaN      NaN          NaN          NaN          NaN
1046      NaN      NaN          NaN          NaN          NaN
1049      NaN      NaN          NaN          NaN          NaN
1050      NaN      NaN          NaN          NaN          NaN
1091      NaN      NaN          NaN          NaN          NaN
1180      NaN      NaN          NaN          NaN          NaN
1217      NaN      NaN          NaN          NaN          NaN
1219      NaN      NaN          NaN          NaN          NaN
1233      NaN      NaN          NaN          NaN          NaN
1322      NaN      NaN          NaN          NaN          NaN
1413      NaN      NaN          NaN          NaN          NaN

In [ ]:
#par rapport au définition tous ces NaN ne sont des non définis mais une absence de l'objet considéré
#donc création d'une variable "No"

In [82]:
df_train["BsmtQual"]=df_train["BsmtQual"].fillna("No")
df_train["BsmtCond"]=df_train["BsmtCond"].fillna("No")
df_train["BsmtExposure"]=df_train["BsmtExposure"].fillna("No")
df_train["BsmtFinType1"]=df_train["BsmtFinType1"].fillna("No")
df_train["BsmtFinType2"]=df_train["BsmtFinType2"].fillna("No")

In [83]:
df_train["BsmtExposure"].unique()

array(['No', 'Gd', 'Mn', 'Av'], dtype=object)

In [84]:
df_train["BsmtQual"].unique()

array(['Gd', 'TA', 'Ex', 'No', 'Fa'], dtype=object)

In [ ]:
# 41  Electrical     1459 non-null   object 

In [85]:
df_train["Electrical"].unique()
# La définition n'aide pas pour ce NaN

array(['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix', nan], dtype=object)